import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "./providers";
import { Suspense } from "react"; //for useSearchParams bug
import { Auth0Provider } from "@auth0/nextjs-auth0";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <Suspense fallback={null}>
            <Header />
          </Suspense>

          <main className="container mx-auto px-4">
            <Auth0Provider>
              {children}
            </Auth0Provider>
          </main>

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
